require_relative 'models/node'
require_relative 'models/edge'
require_relative 'models/graph'
require_relative 'models/model'
require_relative 'models/barabasi_albert'
require_relative 'models/watts_strogatz'
